[package]
name = "minter-meta"
version = "0.1.0"
edition = "2018"
publish = false
authors = ["Micha Vie <micha@peerme.io>", "Spawnable <hello@spawnable.io>"]

[dev-dependencies]

[dependencies.minter]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.42.0"
